dist: trusty
addons:
  chrome: stable
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.arquillian"

script:
- mvn clean test -Ptests -Darquillian.browser=phantomjs
